const Necks = {
  '12103': {
    itemId: '12103',
    name: '秘术之星',
    icon: 'https://wow.zamimg.com/images/wow/icons/tiny/inv_jewelry_talisman_08.gif',
    quality: QUALITY.RARE,
    stamina: 9,
    intellect: 9,
    spirit: 9,
    spell_hit: 1,
  },
  '17109': {
    itemId: '17109',
    name: '启示项链',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/inv_jewelry_necklace_10.jpg',
    quality: QUALITY.EPIC,
    stamina: 9,
    intellect: 10,
    spirit: 10,
    spell_damage: 18,
  },
  '18814': {
    itemId: '18814',
    name: '火焰之王的项圈',
    icon: 'https://wow.zamimg.com/images/wow/icons/large/inv_jewelry_amulet_05.jpg',
    quality: QUALITY.EPIC,
    stamina: 7,
    intellect: 7,
    spell_damage: 34,
  },
};
